# Generated by Django 5.2.7 on 2025-10-27 08:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('centers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GenderTB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=31, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PositionTB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(blank=True, choices=[('Manager', 'Manager'), ('Employee', 'Employee'), ('CEO', 'CEO')], max_length=155, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileTB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profilePic', models.ImageField(blank=True, null=True, upload_to='profile_picture/')),
                ('age', models.IntegerField(blank=True, null=True)),
                ('desc', models.TextField(blank=True, null=True)),
                ('meliCardPic', models.ImageField(blank=True, null=True, upload_to='melicard_picture/')),
                ('personnelCode', models.IntegerField(blank=True, null=True)),
                ('otp_code', models.CharField(blank=True, max_length=15, null=True)),
                ('center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profileCenter', to='centers.centertb')),
                ('gender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ProfileGender', to='allusers.gendertb')),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ProfilePosition', to='allusers.positiontb')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ProfileUser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
