# Generated by Django 5.2.7 on 2025-11-06 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allusers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profiletb',
            name='meliCardPic',
        ),
        migrations.AddField(
            model_name='profiletb',
            name='meliCardCode',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profiletb',
            name='phone',
            field=models.IntegerField(blank=True, max_length=13, null=True),
        ),
    ]
